### PR TITLE
Move get script into this repository

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Moving the get-script into this repository for easy CRI-O bundle retrieval.
#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/7380
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Moved get script into this repository
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by haircommander** [comment]
/lgtm
 
note to self: update https://github.com/kubernetes/test-infra/blob/811baf28f3cd6255c04b30128b5edc52e319ac6e/jobs/e2e_node/crio/templates/base/root.yaml#L89 before removing the cri-o one

**Comment by haircommander** [comment]
https://github.com/kubernetes/test-infra/pull/31077

**Comment by saschagrunert** [comment]
> /lgtm
> 
> note to self: update https://github.com/kubernetes/test-infra/blob/811baf28f3cd6255c04b30128b5edc52e319ac6e/jobs/e2e_node/crio/templates/base/root.yaml#L89 before removing the cri-o one

This is pinned to a specific commit, so it should be fine if we just migrate at some point in time.

**Pull request merged**
